### ISSUE TITLE
Additional: Add an about us page

### ISSUE THREAD

**Issue by kimikoesc** [teamtempo/mysouschef-native#31]

**Comment by jamesbalcombe83** [comment]
Text on page to click
- © Team Tempo 2021
Text for the modal
- About Us
- mysouschef was developed by Team Tempo for their senior project whilst at Code Chrysalis - a full stack coding bootcamp in Tokyo.
- Team Tempo are
- Kim Escovilla (your githandle or twitter whatever here)
- Valters Klauze (whatever contact he wants here)
- James Balcombe (@CodeWithMrB)
- Please feel free to get in touch with us
