### ISSUE TITLE
Fix: Aesthetic issues

### ISSUE THREAD

**Issue by jamesbalcombe83** [teamtempo/mysouschef-native#83]
At least on my phone, the Team Tempo 2021 text is too far down - the bottom of the "p" in tempo is offscreen and not visible, so maybe push that text a teeny bit further up the screen?

Show instructions button - text could use a little more breathing room inside button

Capitalization of text is inconsistent - e.g. "edit timer" is all lowercase, "Show Instructions" is both words uppercase

There is black text on light green in some places, and white text on light green in others. The white text seems to work (would crosscheck for accessibility in contrast) but the black text on light green feels a bit rough. Maybe try making the black text a very dark version of the green instead of outright black, so it looks more cohesive with its background?

**Comment by kimikoesc** [comment]
#86
